export * from './sales.component'
export * from './customer/customer.component';
export * from './salesOrder/SOrder.component';
export * from './salesOrder/header/header.component';
export * from './salesOrder/detail/detail.component';
export * from './salesOrder/payment/payment.component';
export * from './salesReps/salesRep.component';
export * from './salesPayment/payment.component';
export * from './commission/commission.component';
export * from './provinces/province.component';
export * from './regions/region.component';