export * from './pages.component';
export * from './Materials/Accessories/accessories.component';
export * from './Materials/cloth/cloth.component';
export * from './dashboard/dashboard.component';
export * from './user/user.component';
export * from './profile/profile.component';
export * from './chngpass/chngpass';
export * from './login/login.component';
export * from './sales/index';
export * from './expanses/expanse.component'